### ISSUE TITLE
Purpose of this project

### ISSUE THREAD

**Issue by beloso** [ReactiveCocoa/ReactiveObjC#26]
Hi,

I've been using `ReactiveCocoa` locked to the last Objective C version

Only today I became aware of this project.

Is this meant to be a "replacement" for ReactiveCocoa version 2.5?

Can I safely assume that I can replace `ReactiveCocoa` in my podfile to `ReactiveObjC`?

Will this project have future updates?

**Comment by mdiep** [comment]
This is the successor to ReactiveCocoa 2.5 since RAC is now Cocoa bindings on top of ReactiveSwift.

Any maintenance updates to the Objective-C code will be done here. I'm not personally interested in updating the project beyond that, but it's possible that some people might be. They're welcome to contribute. ☺️

**Comment by beloso** [comment]
Thank you!!
