### ISSUE TITLE
flattenMap new return type

### ISSUE THREAD

**Issue by beloso** [ReactiveCocoa/ReactiveObjC#77]
I am in the process of migrating from ReactiveCocoa 2.5 to ReactiveObjC 2.1.2

I've noticed that `flattenMap`'s return type changed from `RACStream` to `__kindOf RACSignal`

Shouldn't have changed to `__kindOf RACStream` as `RACSignal` continues to be a subclass of `RACStream`?

**Comment by mdiep** [comment]
Maybe? I think this was done to make generics work well.

Are you actually returning a `RACStream`?

**Comment by beloso** [comment]
I am not returning a `RACStream`, I've noticed the change when migrating. All my `flattenMap`s were returning `RACStream`, but I always return a `RACSignal`. A simple find and replace fixed this for me.

I just wondered if the change was deliberate or a mistake perhaps.

**Comment by beloso** [comment]
I changed to ReactiveObjC specifically for the generics. So there is no need to change this back to `RACStream` on my end.

**Comment by erichoracek** [comment]
When I was updating the annotations, I checked this behavior. Returning a `RACSequence` from within the block provided to a `-[RACSignal flattenMap:]` will cause a crash. See https://github.com/ReactiveCocoa/ReactiveObjC/blob/master/ReactiveObjC/RACSignal.m#L108-L176 — specifically that the `bindBlock()`'s return value is cast to a `RACSignal *` and `subscribeNext:` is invoked on it, which is only available on `RACSignal`, not `RACSequence`.

It would appear that `flattenMap:` is not truly available on `RACStream` since `bind:` is not implemented on `RACStream` (subclasses must implement it). It seems best to think of `RACStream` as an protocol with some extensions that `RACSignal` and `RACSequence` both share, but they are generally not interoperable in practice.

**Comment by beloso** [comment]
Thank you for your awesome explanation. It does indeed make sense to have change it to a `RACSignal`. I've never returned anything else actually.
