### ISSUE TITLE
[Question] iOS 7 Support

### ISSUE THREAD

**Issue by AYastrebov** [ReactiveCocoa/ReactiveObjC#93]
Will this work for iOS 7 deployment target?

**Comment by erichoracek** [comment]
The minimum deployment target of ReactiveObjC is iOS 8, so unfortunately it will not without making some changes. While I can't comment on the amount of work that would be necessary to make this change, someone else may be able to. However, I'm not sure this is something that we'd want to merge, since it would complicate dynamic framework support (and iOS 8 and below is [less than 3%](https://mixpanel.com/trends/#report/ios_10) of iOS users).

**Comment by erichoracek** [comment]
You may have luck with an old version of ReactiveCocoa though (pre 3.0), which includes this same API.

**Comment by iv-mexx** [comment]
Yes, I'm still successfully using Reactive Cocoa 2.5 in one particular project that still supports iOS 7. 
```
pod 'ReactiveCocoa', '~> 2.5'
```
