### ISSUE TITLE
Make it possible to pass RACSignalAsynchronousWaitTimeout

### ISSUE THREAD

**Issue by jcavar** [ReactiveCocoa/ReactiveObjC#95]
Hi,

`RACSignalAsynchronousWaitTimeout` is used in `- (id)asynchronousFirstOrDefault:(id)defaultValue success:(BOOL *)success error:(NSError **)error` but it is not possible to change that value. If test is expected to take longer then defined value, it will fail.

Would it be possible to create alternative method that accepts this value as well?

**Comment by erichoracek** [comment]
I've found in the past that when I'm bumping up against the time limits of the `asynchronous...` family of methods in tests, the solution is typically to attempt to speed up the test rather than increase the duration of the wait.

With respect to adding a new method, I'd learn towards actively discouraging long-running test methods in ReactiveObjC unless there's a very good use case for allowing custom wait durations.

However, if you absolutely need a longer timeout, it should be relatively easy to roll your own `asynchronous...` wait method as a `RACSignal` extension.

**Comment by jcavar** [comment]
We are using it for performance testing with quite large data set, so we expect it to be longer then 10, especially on our Jenkins machines that are relatively slow.

But regardless of that I think allowing to pass dependency is generally good idea. Someone maybe needs shorter time interval. And we can still keep default value 10.

**Comment by erichoracek** [comment]
That use case seems like something that could be supported by ReactiveObjC if you'd want to take a stab at it. We'd likely want to keep the original `asynchronous...` methods but add another set that takes an extra `timeout:(NSTimeInterval)` for backwards compatibility.

**Comment by jcavar** [comment]
Yes, that makes sense. Cool, I will then work on this when I have some free time and will post PR
